#!/usr/bin/env python3
"""Build deep academic interpretation guides for all 80 charts."""
import os, re

VIZ_DIR = "visualizations"

GUIDE_CSS = '''<!--ATLAS-GUIDE-START-->
<style>
.guide{position:relative;z-index:1;background:#080B13;padding:36px 5% 50px;color:#C8D0DA;
font-family:'Source Sans 3','Segoe UI',system-ui,sans-serif;font-size:.84rem;line-height:1.75;border-top:2px solid #151d2e}
.guide-inner{max-width:1100px;margin:0 auto}
.guide h2{color:#00D5E0;font-size:1.15rem;font-weight:700;margin:0 0 4px;font-family:'Playfair Display',Georgia,serif}
.guide .tagline{color:#FF5872;font-size:.92rem;font-weight:600;margin:0 0 16px;font-style:italic}
.guide h3{color:#FFD700;font-size:.88rem;font-weight:700;margin:22px 0 6px;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #1a2233;padding-bottom:4px}
.guide p{margin:0 0 10px;color:#B8C4D0;text-align:justify}
.guide .hl{background:#0f1520;border-left:3px solid #00D5E0;padding:12px 16px;margin:10px 0;border-radius:0 6px 6px 0}
.guide .warn{border-left-color:#FF5872}
.guide .gold{border-left-color:#FFD700}
.guide .insight{border-left-color:#B10DC9}
.guide b{color:#E8ECF0}.guide em{color:#FFD700;font-style:normal}
.guide code{background:#1C2333;padding:1px 6px;border-radius:3px;font-size:.76rem;color:#00D5E0}
.guide .cols{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:10px 0}
@media(max-width:900px){.guide .cols{grid-template-columns:1fr}}
.guide .cols>div{background:#0c1018;border-radius:6px;padding:14px 16px;border:1px solid #151d2e}
.guide .cols h4{color:#00D5E0;font-size:.8rem;margin:0 0 6px;font-weight:700}
</style>'''

GUIDE_END = '<!--ATLAS-GUIDE-END-->'

G = {}

G["01"] = '''<h2>Wealth vs Health of Nations</h2>
<p class="tagline">Does money buy life? The most important scatter plot in the history of public health.</p>

<h3>What You Are Seeing</h3>
<p>Each bubble is one country in one year. The <b>horizontal axis</b> shows GDP per capita in Purchasing Power Parity (PPP) dollars on a <em>logarithmic scale</em>: each major gridline represents a tenfold increase in national income. The <b>vertical axis</b> shows life expectancy at birth in years. <b>Bubble size</b> encodes total population, making India and China visually dominant. <b>Color</b> distinguishes continents. The <b>animation slider</b> at the bottom steps through years 1990 to 2023, letting you watch three decades of development unfold.</p>

<h3>The Science: The Preston Curve and Its Implications</h3>
<p>This chart visualizes one of the most robust empirical relationships in the social sciences: the <b>Preston Curve</b>, first documented by demographer Samuel Preston in 1975. Preston showed that national income strongly predicts population health, but with a crucial non-linearity: the curve is steep at low incomes and flattens at high incomes. The logarithmic X-axis is not cosmetic; it reflects the biological reality that the relationship between wealth and health is logarithmic. Going from $1,000 to $5,000 GDP per capita adds roughly 15 years of life expectancy (through basic sanitation, nutrition, childhood vaccination, and primary healthcare). Going from $50,000 to $100,000 adds perhaps 1-2 years. This diminishing return is the central insight.</p>
<div class="hl">The curve has also <b>shifted upward over time</b>. A country with $5,000 GDP per capita today has higher life expectancy than a country at $5,000 in 1970, because medical technology, public health knowledge, and international health interventions (WHO programmes, GAVI vaccinations) have improved outcomes independent of national income. This upward shift is visible when you drag the animation slider: the entire cloud moves up and right simultaneously. The shift contradicts crude economic determinism: <b>global knowledge spillovers matter independently of local wealth</b>.</div>

<h3>Understanding the Axes and Transformations</h3>
<div class="cols">
<div><h4>GDP per Capita (PPP $) [X-axis, log scale]</h4>
<p>Total economic output (Gross Domestic Product) divided by total population, adjusted for local purchasing power parity. A value of $10,000 means a person could buy goods equivalent to $10,000 in the United States. PPP adjustment is essential: $1,000 in India buys far more food, housing, and services than $1,000 in Switzerland. Without PPP, the chart would dramatically overstate the deprivation of low-income countries. The <em>log scale</em> is used because the relationship is logarithmic: equal percentage increases in income yield roughly equal absolute increases in life expectancy. On a linear scale, all countries below $10,000 would be compressed into a narrow band on the left, obscuring the steepest and most policy-relevant part of the curve.</p></div>
<div><h4>Life Expectancy at Birth [Y-axis, linear]</h4>
<p>The average number of years a newborn is expected to live under current age-specific mortality conditions. This is a <em>period measure</em>, not a cohort prediction: it describes today's mortality rates, not future improvements. Values below 55 indicate severe health crises (active conflict, HIV/AIDS epidemics, famine). Values of 60-70 are typical of lower-middle-income countries with functional but strained health systems. Above 75 is the norm for upper-middle and high-income countries. The biological maximum appears to be around 85-87 years under current medical technology, which is why the curve flattens at high incomes: no amount of wealth can (yet) push life expectancy much beyond that ceiling.</p></div>
</div>

<h3>What the Movement Means</h3>
<p>When a bubble moves <b>rightward</b> over time, the country is getting richer in real per-capita terms. <b>Upward</b> movement means improving health outcomes. The ideal trajectory is toward the upper-right. Countries moving <b>leftward</b> are rare and indicate economic contraction (Venezuela in the 2010s, post-Soviet states in the early 1990s). Countries moving <b>downward</b> are even rarer and indicate health catastrophes: Botswana and South Africa dipped during the HIV/AIDS epidemic of the 1990s-2000s (losing 10-15 years of life expectancy) before antiretroviral therapy enabled recovery. Rwanda shows a sharp downward spike in 1994 (genocide) followed by one of the fastest recoveries in modern development history.</p>

<h3>Spatial and Geographic Dimensions</h3>
<div class="hl gold">The continental clustering is not random: it reflects deep geographic determinants of development. Sub-Saharan African countries (cyan) cluster in the bottom-left due to a combination of factors that geographers and development economists have debated for decades: the <b>tropical disease burden</b> (malaria, sleeping sickness, schistosomiasis), <b>agricultural productivity constraints</b> (poor soils, erratic rainfall, lack of temperate cereal crops), <b>colonial extraction legacies</b> (institutions designed to extract resources rather than build human capital, per Acemoglu, Johnson, and Robinson 2001), and <b>geographic isolation</b> (landlocked countries, poor natural harbors, distance from global trade routes). Jeffrey Sachs (2001) argued that geography itself, particularly tropical location, is the primary driver of poverty. Acemoglu et al. countered that institutions (shaped by colonial history) matter more. This chart cannot resolve that debate, but the continental clustering is consistent with both hypotheses.</div>

<h3>Socio-Political and Policy Implications</h3>
<div class="hl warn">For countries on the <b>steep part</b> of the curve (below ~$10,000 GDP per capita), <b>economic growth is the most powerful health intervention available</b>. Growth funds hospitals, trains doctors, builds water and sanitation systems, and creates the tax base for public health programmes. For these countries, trade liberalization, infrastructure investment, agricultural modernization, and political stability are health policies, even though they do not appear in any health ministry budget. For countries on the <b>flat part</b> (above ~$30,000), further GDP growth yields minimal health gains. Here, the policy frontier shifts to: reducing <em>inequality</em> (within-country inequality reduces the average life expectancy by concentrating health resources among the wealthy), addressing <em>lifestyle diseases</em> (obesity, mental health, substance abuse), improving <em>elder care</em>, and tackling <em>social determinants of health</em> (loneliness, housing quality, air pollution). The United States is a cautionary example: it has the highest GDP per capita among large nations but ranks 46th in life expectancy, largely due to inequality, lack of universal healthcare, and the opioid crisis. This demonstrates that <b>wealth is necessary but not sufficient</b> for population health.</div>

<h3>Anthropological Perspective</h3>
<p>The health transition visible in this animation is one of the most profound transformations in human history. For 99% of human existence, life expectancy was 25-35 years. The dramatic increase to 70+ years in most of the world occurred in just the last 150 years, and the developing-world component of that increase occurred primarily in the last 50 years. This is not merely a statistical curiosity: it represents a fundamental change in the human experience of mortality. In high-mortality societies, death is a constant companion from childhood. In low-mortality societies, death becomes an event of old age. This shift transforms family structures (fewer children, more investment per child), economic behavior (longer time horizons, greater willingness to invest in education), and political expectations (citizens who expect to live long lives demand more from their governments). The animation captures this civilizational transformation compressed into 33 seconds.</p>'''

G["37"] = '''<h2>LISA Cluster Map: Where Electoral Behavior Clusters Geographically</h2>
<p class="tagline">Not all votes are independent. Geography shapes democracy in ways that challenge the one-person-one-vote ideal.</p>

<h3>What You Are Seeing</h3>
<p>Two maps of India's 543 parliamentary constituencies, side by side. The <b>left panel</b> shows spatial clusters of voter turnout. The <b>right panel</b> shows spatial clusters of victory margin. Each constituency is classified into one of five categories based on Local Indicators of Spatial Association (LISA). <b>Red dots (Hot Spots)</b>: constituencies with high values surrounded by neighbors with high values. <b>Blue dots (Cold Spots)</b>: low values surrounded by low values. <b>Orange (High-Low)</b>: a high-value outlier in a low-value neighborhood. <b>Cyan (Low-High)</b>: the reverse. <b>Grey</b>: not statistically significant at p < 0.05.</p>

<h3>The Science: Spatial Autocorrelation and Moran's I</h3>
<p><b>Spatial autocorrelation</b> is the tendency for nearby geographic units to have similar attribute values. It is formally quantified by <b>Moran's I</b> statistic, developed by Patrick Moran in 1950. The formula is:</p>
<div class="hl"><code>I = (n / W) x [&Sigma;<sub>i</sub> &Sigma;<sub>j</sub> w<sub>ij</sub>(x<sub>i</sub> - x&#772;)(x<sub>j</sub> - x&#772;)] / [&Sigma;<sub>i</sub> (x<sub>i</sub> - x&#772;)<sup>2</sup>]</code><br><br>
Where <b>n</b> = number of spatial units (543 constituencies), <b>x<sub>i</sub></b> = the variable value at unit <em>i</em>, <b>x&#772;</b> = the mean across all units, <b>w<sub>ij</sub></b> = the spatial weight between units <em>i</em> and <em>j</em>, and <b>W</b> = the sum of all weights. The statistic ranges from approximately -1 (perfect dispersion: every unit is surrounded by units with opposite values) through 0 (random spatial pattern) to +1 (perfect clustering: identical values near each other).</div>
<p>For voter turnout, <b>I = 0.642</b> (p < 0.001, z = 34.2). This is extremely strong positive spatial autocorrelation, meaning that <b>neighboring constituencies have very similar turnout rates</b>. For comparison, Moran's I values above 0.3 are considered strong in most social science applications. The turnout clustering is among the strongest spatial patterns in Indian electoral data. For victory margin, <b>I = 0.260</b> (p < 0.001), indicating moderate but significant clustering.</p>

<h3>How the Spatial Weights Were Constructed</h3>
<p>We used <b>K-Nearest Neighbors (KNN) with k = 8</b>: for each constituency, its 8 geographically closest neighbors (measured by centroid-to-centroid Euclidean distance) are assigned a weight of 1; all others receive 0. Weights are then <b>row-standardized</b> (each row sums to 1) so that each neighbor contributes equally regardless of the total number of neighbors. This means the spatial lag (neighbors' average) for any constituency is simply the mean of its 8 nearest neighbors' values. We chose KNN over Queen contiguity because the DataMeet constituency polygon boundaries have precision issues that cause some geometrically adjacent constituencies to fail the Queen adjacency test.</p>

<h3>LISA: Decomposing the Global Pattern into Local Clusters</h3>
<p><b>LISA</b> (Local Indicators of Spatial Association, Anselin 1995) decomposes the global Moran's I into per-location contributions. Each constituency receives a local I<sub>i</sub> value. When I<sub>i</sub> is positive and the constituency's value is above the mean, it is classified as <b>High-High (Hot Spot)</b>: this constituency and its neighbors are all high. When I<sub>i</sub> is positive and the value is below the mean, it is <b>Low-Low (Cold Spot)</b>. Negative I<sub>i</sub> values indicate <b>spatial outliers</b>. Statistical significance is assessed through <b>conditional permutation inference</b>: the observed I<sub>i</sub> is compared to 999 random reshufflings of the data, and only those with p < 0.05 (fewer than 5% chance of occurring under spatial randomness) are colored.</p>

<h3>What the Clusters Reveal</h3>
<div class="hl gold"><b>Turnout Hot Spots</b> (150 constituencies, red): concentrated in <b>Kerala, Tamil Nadu, and West Bengal</b>. These states share characteristics that foster high civic engagement: high literacy rates (Kerala: 94%, Tamil Nadu: 80%), strong political party organizations with deep grassroots networks, competitive multi-party systems that incentivize mobilization, and a history of social reform movements (anti-caste, communist, Dravidian) that politicized large sections of the population. The geographic clustering means that <b>high turnout is socially contagious</b>: voters in high-turnout neighborhoods are exposed to more political discussion, more party canvassing, and stronger social norms around voting.<br><br>
<b>Turnout Cold Spots</b> (170 constituencies, blue): concentrated in <b>Uttar Pradesh, Bihar, and parts of Madhya Pradesh</b>. These states have lower literacy (Bihar: 64%, UP: 70%), weaker party organization at the booth level, larger and more geographically dispersed constituencies, and higher rates of caste-based social fragmentation that can suppress collective action. Crucially, women's turnout is especially low in these cold spots: gender norms restricting women's mobility reduce their ability to reach polling stations, particularly in rural areas.</div>

<h3>Spatial Science: Tobler's First Law and Electoral Contagion</h3>
<p>The LISA results confirm <b>Tobler's First Law of Geography</b> (1970): "Everything is related to everything else, but near things are more related than distant things." Applied to elections, this means that voter behavior is not determined solely by individual characteristics (income, education, caste) but also by <b>geographic context</b>. A low-income voter in a high-turnout neighborhood (Kerala) is more likely to vote than a similar low-income voter in a low-turnout neighborhood (rural Bihar). This "neighborhood effect" (Johnston et al. 2001) operates through social networks, party infrastructure, and local political culture, all of which are geographically bounded.</p>

<h3>Policy Implications: Spatial Targeting of Democratic Interventions</h3>
<div class="hl warn"><b>Cold spot constituencies</b> need spatially targeted interventions: (1) More polling stations per voter (the current norm of one station per 1,200-1,500 voters is inadequate in geographically large rural constituencies where voters may need to travel 10+ km). (2) Voter awareness campaigns in local languages, delivered through community radio and self-help groups. (3) Women-specific mobilization: transportation to polling stations, all-women polling booths, and campaigns addressing family-level barriers to women voting. (4) Booth-level party competition: cold spots often lack genuine multi-party contest, reducing the incentive to mobilize voters.<br><br>
<b>Hot spot regions</b> demonstrate that high civic engagement can be cultivated over decades through sustained investment in literacy, competitive political institutions, and local governance (panchayati raj). The spatial clustering means that <b>interventions in one constituency can spill over to neighbors</b> through demonstration effects and shared social networks, suggesting that area-based approaches (targeting clusters rather than individual constituencies) may be more efficient than constituency-by-constituency programmes. The Election Commission's Systematic Voters' Education and Electoral Participation (SVEEP) programme should be redesigned with explicit spatial targeting based on these LISA results.</div>'''

G["65"] = '''<h2>The Silence Map: 152 Constituencies Where No Woman Even Ran</h2>
<p class="tagline">Before asking why women lose elections, ask why they never appear on the ballot.</p>

<h3>What You Are Seeing</h3>
<p>All 543 Lok Sabha constituencies on the India map. <b>Red X markers</b> (large, impossible to miss) identify the 152 constituencies where <em>not a single woman filed her candidacy</em> in the 2024 general election. <b>Orange dots</b> = exactly 1 woman candidate. <b>Yellow</b> = 2-3 women. <b>Green</b> = 4 or more. Data: Election Commission of India, verified against candidate-level filing records.</p>

<h3>The Scale of Exclusion</h3>
<div class="hl warn"><b>152 out of 543 = 28%.</b> More than one in four of India's parliamentary constituencies held an election in 2024 where every single candidate was male. This is not a "glass ceiling" problem (where women run but cannot win). This is a <b>"missing staircase" problem</b>: women are absent from the starting line entirely. In these constituencies, no voter, regardless of their preference, had the option of electing a woman. The democratic principle of choice was constrained before a single vote was cast.</div>

<h3>The Spatial Pattern: Geography of Exclusion</h3>
<p>The red Xs are not randomly distributed. They cluster in specific geographic and socio-cultural zones:</p>
<div class="cols">
<div><h4>Where Women Are Absent</h4>
<p><b>Central Uttar Pradesh</b>: the Awadhi and Bundelkhand belts, characterized by strong feudal social structures, low female literacy (below 55% in many districts), high rates of child marriage, and deeply patriarchal political party structures. <b>Rural Bihar</b>: similar social indicators, compounded by extreme poverty and caste-based political mobilization that marginalizes gender concerns. <b>Parts of Rajasthan</b>: the desert belt where women's mobility is severely restricted by purdah norms. <b>Rural Maharashtra</b>: the Vidarbha and Marathwada regions where agrarian distress dominates political discourse, and women's political participation is treated as secondary.</p></div>
<div><h4>Where Women Do Contest</h4>
<p><b>Southern India</b> (Kerala, Tamil Nadu, Karnataka): higher female literacy, stronger women's self-help group networks, and political parties with more inclusive nomination cultures. <b>Urban constituencies</b> (Delhi, Mumbai, Kolkata, Bangalore): media access, educated electorates, and party calculations that women candidates appeal to urban voters. <b>Northeast India</b> (Manipur, Meghalaya, Mizoram): matrilineal or gender-egalitarian tribal cultures where women's public participation is normalized.</p></div>
</div>

<h3>Why the Silence? A Multi-Level Analysis</h3>
<p><b>Level 1: Party Gatekeeping.</b> In India, candidate selection is controlled by party high commands, not primary elections. Parties nominate candidates based on "winnability" assessments that systematically disadvantage women. The unstated logic: "women cannot win here, so why nominate them?" This creates a self-fulfilling prophecy. Data from this atlas (Chart 46) shows that women who ARE nominated win at rates comparable to men, suggesting the winnability concern is unfounded.</p>
<p><b>Level 2: Financial Barriers.</b> Contesting a Lok Sabha election costs an estimated Rs 5-15 crore (informally). Women, who control far less household wealth, face a structural funding gap. The security deposit alone (Rs 25,000 for General, Rs 12,500 for SC/ST) is modest, but campaign expenses dwarf it.</p>
<p><b>Level 3: Safety and Social Norms.</b> Women candidates, particularly in rural North India, face harassment, threats, and social ostracism. In the red-X constituencies, local power structures (often caste-based or feudal) actively discourage women from entering politics. The "honour" of the family is seen as incompatible with the public exposure of campaigning.</p>
<p><b>Level 4: Spatial Factors.</b> The red-X constituencies tend to be <b>geographically larger</b> (more area to cover while campaigning), <b>more rural</b> (fewer media outlets, more reliance on physical canvassing), and <b>more socially fragmented</b> (multiple caste and religious communities that require separate outreach). These spatial characteristics make campaigning harder and more expensive for any candidate, but disproportionately so for women who face additional mobility constraints.</p>

<h3>The Anthropology of Political Silence</h3>
<div class="hl insight">The absence of women from 28% of ballots is not merely a statistical gap; it is a form of <b>structural violence</b> (Galtung, 1969). It is violence because it systematically prevents a group from participating in the decisions that govern their lives. It is structural because it is embedded in institutions (party nomination processes), social norms (purdah, "honor"), and spatial arrangements (large rural constituencies) rather than in individual acts of discrimination. The spatial clustering of this silence in the Hindi heartland reveals that <b>India's gender problem in politics is not national but regional</b>: it is concentrated in specific socio-geographic zones where patriarchal institutions are strongest and reformist movements (Dravidian, communist, tribal rights) never took root.</div>

<h3>Policy: What Would Fix This?</h3>
<div class="hl warn"><b>The Women's Reservation Bill (33%)</b>, passed by Parliament in 2023 but not yet implemented, would reserve approximately 181 constituencies (rotating each election) for women candidates. This would force parties to nominate women in exactly the kind of constituencies currently showing red Xs. Without this structural mandate, 75 years of Indian democracy have produced only incremental improvement: from ~5% women MPs in the 1950s to ~8.7% today. The spatial evidence from this chart is unambiguous: <b>voluntary change has failed in the red-X zones</b>. Only a legislative mandate will break the cycle. Additionally: (1) public funding of women candidates would reduce the financial barrier; (2) party-level quotas (requiring 33% women nominees even for unreserved seats) would build a pipeline of experienced women politicians; (3) constituency-level safety infrastructure (more women police stations, anti-harassment cells) would reduce the physical risks of campaigning.</div>'''

G["72"] = '''<h2>Fiscal Returns: The Tax Inequality Map of India</h2>
<p class="tagline">For every Rs 100 you pay in taxes, how much does your state get back? The answer reveals India's deepest federal fracture.</p>

<h3>What You Are Seeing</h3>
<p>A diverging horizontal bar chart showing, for each major Indian state, <b>how many rupees it receives from the central government for every Rs 100 its residents pay in central taxes</b>. The <b>gold dashed line at Rs 100</b> marks break-even. States to its left are <em>net contributors</em> (they pay more in taxes than they receive in transfers). States to its right are <em>net recipients</em>. Data source: 15th Finance Commission recommendations, Reserve Bank of India.</p>

<h3>How India's Fiscal Architecture Works</h3>
<p>India collects most tax revenue centrally (income tax, GST, corporate tax). The <b>Finance Commission</b>, a constitutional body reconstituted every 5 years, recommends how this revenue should be shared with states. The 15th Finance Commission (2020-2025) distributes 41% of central tax revenue to states using a formula with these weights:</p>
<div class="cols">
<div><h4>The Formula</h4>
<p><b>Income Distance (45%)</b>: the gap between a state's per-capita income and the highest state's income. Poorer states get more. This is the largest driver of redistribution.<br>
<b>Population (15%)</b>: based on the 2011 Census. More populous states get more.<br>
<b>Area (15%)</b>: larger states get more (to fund geographically dispersed services).<br>
<b>Demographic Performance (12.5%)</b>: states that achieved lower fertility (population control success) get a small bonus.<br>
<b>Forest and Ecology (10%)</b>: states with more forest cover get more (to compensate for foregone development).<br>
<b>Tax Effort (2.5%)</b>: states that collect more of their own-source revenue get a small bonus.</p></div>
<div><h4>What the Numbers Mean</h4>
<p><b>Tamil Nadu: Rs 29.7</b>. For every Rs 100 Tamilians pay in central taxes, their state receives Rs 29.7 in transfers. The "missing" Rs 70.3 subsidizes other states.<br>
<b>Delhi: Rs 15.2</b>. The most extreme contributor, reflecting its very high income and tax base relative to its small population.<br>
<b>Bihar: Rs 142.5</b>. Bihar receives Rs 42.5 more per person than its population pays. This reflects Bihar's low income (triggering the Income Distance criterion) and large population.<br>
<b>Arunachal Pradesh: Rs 510.3</b>. Extreme net recipient due to tiny population, large area, extensive forest cover, and very low income.</p></div>
</div>

<h3>The "Double Whammy" Argument</h3>
<div class="hl warn">Southern states (Tamil Nadu, Karnataka, Kerala, Andhra Pradesh, Maharashtra) face a <b>compounding penalty</b> that has become the defining grievance of Indian fiscal federalism:<br><br>
<b>First penalty (fiscal)</b>: They invested heavily in education, healthcare, and family planning over the past 50 years. This investment produced economic growth, which raised their income levels. Higher income means they pay more central taxes AND receive less under the Income Distance formula. They are financially punished for their own success.<br><br>
<b>Second penalty (representational)</b>: Their investment in family planning reduced population growth. Under population-based delimitation (when it is eventually implemented based on post-2026 Census data), they will <b>lose Lok Sabha seats</b> because their populations grew more slowly than northern states. They will have less voice in Parliament to advocate for their fiscal interests.<br><br>
The "double whammy": <b>southern states subsidize northern states fiscally AND lose political representation to them</b>. Northern states (UP, Bihar, Rajasthan), which did not invest as aggressively in population control, gain both more seats AND more fiscal transfers. This creates a <b>perverse incentive against demographic responsibility</b>.</div>

<h3>Geographic and Spatial Dimensions</h3>
<p>The fiscal gradient is fundamentally <b>spatial</b>: net contributors cluster in the southern and western peninsular states, while net recipients cluster in the northern plains and northeastern hills. This pattern mirrors India's <b>development gradient</b>, which is itself a product of geography (the Indo-Gangetic plain's high population density vs the peninsular south's more moderate density), colonial history (the south's earlier exposure to global trade and missionary education), and post-independence policy choices (southern states invested in human capital while northern states prioritized land reform and patronage politics).</p>

<h3>The Socio-Political Conflict</h3>
<div class="hl gold">This fiscal map is not merely an economic curiosity. It is <b>the most politically explosive dataset in Indian federalism</b>. Tamil Nadu Chief Ministers have publicly cited these numbers when opposing the proposed delimitation of Lok Sabha seats. Karnataka's opposition to the 15th Finance Commission was so intense that the state legislature passed a formal resolution against it. The underlying tension: <b>should India's fiscal union reward good governance or compensate for poverty?</b> The answer, under the current formula, is overwhelmingly the latter. The "Demographic Performance" criterion (12.5% weight) was introduced specifically to address southern grievances, but at one-ninth the weight of Income Distance (45%), it is insufficient to offset the structural disadvantage. Southern economists have proposed increasing it to 25-30%, or introducing entirely new criteria such as <b>women's literacy</b>, <b>human development index</b>, or <b>state-level institutional quality</b>.</div>

<h3>Connecting to Other Charts in This Atlas</h3>
<p>This chart connects directly to: <b>Chart 71</b> (Delimitation Simulator, showing seat redistribution), <b>Chart 75</b> (Punishment Value, combining fiscal penalty with gender analysis), <b>Chart 77</b> (Fiscal Spine, showing the geographic gradient), and <b>Chart 78</b> (Treemap, showing the spatial distribution of "democratic real estate"). Together, these four charts make the case that India's fiscal and representational architecture creates systematic spatial inequality that punishes the most developmentally successful states.</p>'''

# Now generate remaining charts efficiently but with real depth
# I'll write a function that generates substantial content for each
REMAINING = {}

REMAINING["02"] = ("The Demographic Transition in Motion",
"Does money buy life? The most important scatter plot in the history of public health.",
'''<b>X-axis: Fertility Rate</b> (births per woman at current age-specific rates). Above <em>2.1</em> = population growth (replacement level, the 0.1 accounts for child mortality). Below 2.1 = eventual decline without immigration. <b>Y-axis: Life Expectancy</b> at birth. The animation shows each country migrating from the upper-left (high fertility, low life expectancy) toward the lower-right (low fertility, high longevity). This is the <b>Demographic Transition</b>, the most consequential transformation in human history. It is driven by: (1) declining child mortality (parents need fewer births), (2) women's education and labor force participation, (3) contraceptive access, (4) urbanization (children become economic costs rather than assets in cities). <b>Anthropological significance</b>: for 99% of human history, women spent most of their adult lives pregnant or nursing. The transition visible in this animation represents a fundamental change in the lived experience of half of humanity.''',
'''Countries in the <b>upper-left</b> face a <em>youth bulge</em>: massive young populations needing education, jobs, and services. If harnessed (investment in education and employment), this becomes the <b>demographic dividend</b> that propelled East Asian growth in 1970-2000. If neglected, it fuels instability. Countries in the <b>lower-right</b> face aging: pension pressure, labor shortages, and dependency ratios. Japan (1.2), South Korea (0.7), and much of Europe face this challenge. <b>The single most cost-effective intervention</b> for countries in early transition is <em>girls' secondary education</em>, which reliably reduces fertility by 0.5-1.0 children per woman (UNESCO, 2022). <b>Spatially</b>: the transition has a clear geographic pattern, with Sub-Saharan Africa as the last major region to enter it. The trajectory of Nigeria, DRC, Ethiopia, and Tanzania will determine whether world population peaks at 9 or 11 billion.''')

REMAINING["03"] = ("Child Mortality vs Wealth: Humanity's Greatest Achievement",
"Each year, the developing world saves millions more children than the year before. This animation shows how.",
'''<b>Under-5 mortality rate</b>: the probability of dying before age 5, per 1,000 live births. A value of 100 means 10% of children die (common in Sub-Saharan Africa in 1990). Below 10 is the norm in wealthy nations. The <b>log X-axis</b> (GDP per capita, PPP) compresses the wealth scale to reveal patterns among poorer countries. The dramatic global decline from 1990 to 2023 is driven by: (1) <b>oral rehydration therapy</b> (treating diarrhea, the leading child killer), (2) <b>vaccination</b> (measles deaths dropped 73%), (3) <b>insecticide-treated bed nets</b> (malaria), (4) <b>nutrition</b> (breastfeeding campaigns, micronutrient supplementation). The acceleration post-2000 coincides with the Millennium Development Goals, which channeled international funding and political will.''',
'''Every dollar of GDP growth in poor countries translates to children's lives saved. But the curve is not destiny: <b>Bangladesh</b> achieves mortality rates far below what its GDP predicts, proving that targeted public health investment overrides economic constraints. Bangladesh spent heavily on community health workers, oral rehydration, and vaccination campaigns starting in the 1980s. <b>Rwanda</b> achieved similar results after 2000 through a performance-based healthcare system. <b>Policymakers</b> should prioritize: primary healthcare > clean water > childhood vaccination > nutrition > hospital infrastructure. The order matters: investing in hospitals before primary care yields far fewer lives saved per dollar. <b>Spatially</b>: the remaining high-mortality countries are overwhelmingly in the Sahel belt (Mali, Niger, Chad) and conflict zones (Yemen, Somalia), where geographic isolation, poor infrastructure, and insecurity compound the health deficit.''')

# Generate shorter but still substantive entries for all remaining charts
COMPACT = {
"04":"<b>Country Trajectory Traces</b>: 14 nations on the GDP-lifeExp plane over decades. Each line = one country's path through development space. <b>Rightward = richer, upward = healthier, leftward = economic contraction, downward = health crisis</b>. China's dramatic rightward leap reflects market liberalization (1978 onwards). Botswana/South Africa show the HIV/AIDS life expectancy dip (1990s-2000s): a downward loop before antiretroviral therapy enabled recovery. Rwanda's sharp 1994 dip (genocide) is followed by one of the fastest development recoveries in history, demonstrating that institutions and governance can compensate for catastrophic shocks. <b>Policy lesson</b>: development trajectories are not monotonic. Health system resilience (the ability to absorb shocks and recover) is as important as the baseline trajectory. Countries should invest in both growth AND resilience (epidemic preparedness, conflict prevention, climate adaptation).",

"05":"<b>Continental Trends (3 panels)</b>: GDP, life expectancy, and fertility by continent, 1990-2023. <b>Population-weighted</b>: each line reflects what the average person on that continent experiences. Life expectancy is <b>converging</b> (Africa catching up, from 50 to 65+ years). GDP is <b>diverging</b> (the gap between Africa and Europe widening). Fertility is converging (Africa declining toward global norms). <b>Key insight</b>: the health-wealth divergence means that the global health commons (WHO, GAVI, multilateral aid) is succeeding at spreading health improvements, but the market economy is NOT spreading wealth improvements. <b>Policy</b>: health convergence proves targeted interventions work. GDP divergence proves market forces alone will not equalize. Both facts should inform international development strategy.",

"06":"<b>Income Distribution Shift</b>: the disappearance of Rosling's 'two humps'. In 1995, global income had two peaks: a poor-world hump (~$1,000-2,000) and a rich-world hump (~$20,000-40,000). By 2020, they have merged into a single broad peak centered around $5,000-$15,000. This is driven by China (~1.4 billion people) and India (~1.4 billion) pulling into middle income. <b>The remaining left tail</b> (extreme poor) is increasingly concentrated in Sub-Saharan Africa and conflict zones. <b>X-axis is log income</b>: each gridline = 10x increase. Area under curve = population. <b>Policy</b>: global poverty reduction is real and massive, but incomplete. The 'last mile' problem is harder because the remaining extreme poor are in the most difficult governance and geographic environments.",

"07":"<b>Reef Bleaching Hotspots</b>: 27 reef systems. <b>Size = area (km2)</b>. <b>Color = threat level</b>: Critical (>50% coral cover lost, Caribbean and SE Asian reefs), High (significant recent bleaching), Medium, Low. <b>Coral bleaching</b> occurs when ocean temperatures rise 1-2C above the seasonal maximum, causing corals to expel symbiotic zooxanthellae algae. Without these algae, corals starve and die. <b>The Great Barrier Reef</b> experienced mass bleaching in 2016, 2017, 2020, 2022, and 2024. <b>Policy</b>: Marine Protected Areas reduce local stressors (overfishing, pollution, sedimentation) but cannot prevent thermal bleaching from global warming. The Paris Agreement's 1.5C warming target is effectively a <b>reef survival threshold</b>. At 2C, 99% of tropical reefs will experience annual severe bleaching. Current trajectory: 2.5-3C by 2100.",

"08":"<b>Ocean SST Anomaly 1980-2024</b>: global sea surface temperature deviation from the 1971-2000 baseline. <b>Positive values = warmer than historical normal</b>. The upward trend is unambiguous. Mass bleaching events annotated: 1998 (first truly global event, El Nino-driven), 2010, 2016 (strongest, compounded by El Nino + anthropogenic warming), 2024 (shattered all records). <b>The tightening interval between crises</b> (18, 12, 6, 8 years) shows <b>accelerating frequency</b>: recovery time between events is shrinking below the 10-15 years corals need to regrow. <b>Policy</b>: reef management must shift from 'protect and recover' (assuming reefs bounce back between events) to 'adapt and triage' (identifying genetically heat-tolerant populations for conservation and assisted gene flow).",

"09":"<b>Urbanization (Animated Choropleth)</b>: urban population % from 1990 to 2022. <b>Increasing color intensity = more urban</b>. China: 26% to 64%. India: 26% to 35%. Sub-Saharan Africa: 28% to 42%. The global urban transition is the largest migration in human history. By 2050, 68% of humanity will be urban (UN DESA). <b>Policy</b>: countries entering the 30-50% range (current Africa, South Asia) face a critical window. Investment in transit, housing, sanitation, and urban planning NOW determines whether urbanization produces prosperity (as in East Asia) or slums (as in much of South Asia and Africa). The spatial pattern matters: <b>secondary cities</b> (population 500K-2M) are growing faster than megacities and receive less planning attention.",

"10":"<b>Slum Population</b>: % urban residents in slums. <b>Slum</b> (UN-Habitat): housing lacking durable structure, sufficient space, improved water, improved sanitation, or security of tenure. Sub-Saharan Africa and South Asia exceed 50% in many countries. <b>Policy</b>: slum upgrading (providing services to existing settlements: water connections, sanitation, paved paths, land tenure) costs $500-2,000 per household and yields 10-20x returns in health, productivity, and property values. Demolition and relocation costs $5,000-15,000 per household and often increases poverty by destroying social networks and livelihood proximity. <b>The evidence overwhelmingly favors upgrading over demolition</b>.",

"11":"<b>Extreme Poverty ($1.90/day)</b>: population below the World Bank's extreme poverty line, adjusted for purchasing power. <b>Values >40%</b> = nearly half the population in severe deprivation. The geographic concentration in Sub-Saharan Africa reflects compounding disadvantages: conflict (destroying assets and displacing populations), governance failures (corruption diverting aid and investment), geographic disadvantage (tropical disease burden, poor soils, landlocked status), and the colonial legacy of extractive institutions. <b>Policy</b>: cash transfer programmes (GiveDirectly model: unconditional transfers of $500-1000 to extreme poor households) show strong evidence of sustained poverty reduction. Agricultural investment (improved seeds, irrigation, market access) addresses the structural basis of rural poverty. Conflict resolution is prerequisite in many of the worst-affected countries.",

"12":"<b>Gini Inequality Index</b>: 0 = perfect equality, 100 = one person has everything. <b>Calculation</b>: the ratio of the area between the Lorenz curve (cumulative income share vs cumulative population share) and the line of perfect equality, to the total area under the equality line. <b>Gini 25-30</b> (Scandinavia): relatively equal, achieved through progressive taxation, strong unions, and universal public services. <b>Gini 50-63</b> (South Africa, Brazil): extreme concentration, often reflecting racial/ethnic inequality layered onto class inequality. <b>Increasing Gini</b> = the rich getting disproportionately richer (happening in China, India, US since 1980). <b>Decreasing Gini</b> = more equal distribution (happening in Brazil, Latin America since 2000 through conditional cash transfers). <b>Policy</b>: Wilkinson & Pickett (2009) showed that high inequality correlates with worse health, more crime, lower trust, and lower social mobility EVEN controlling for absolute income. This means inequality is not just unfair but functionally harmful.",
}

# India election, 3D, delimitation, women's representation charts
INDIA_3D = {
"38":"<b>Area vs Outcomes</b>: constituency area (log km2) vs turnout and margin. <b>Log transformation</b> handles the 4-order-of-magnitude range (29 km2 urban seats to 180,000 km2 Ladakh). <b>Negative slope</b> for area vs turnout: larger constituencies have systematically lower voter participation. This is not just correlation: larger area means longer travel to polling stations, sparser campaign infrastructure, and higher costs of political information. Area itself is spatially autocorrelated (Moran's I = 0.16, p < 0.001): large constituencies cluster together (Rajasthan, MP, NE India), creating geographic zones of systematic underrepresentation. <b>Policy</b>: the ECI should deploy more polling stations per voter in large-area constituencies, introduce mobile polling units, and expand postal ballot access. The current uniform ratio of ~1 station per 1,200 voters fails to account for geographic dispersal.",

"39":"<b>Moran's I Scatterplot</b>: the fundamental diagnostic tool of spatial statistics. <b>X-axis</b> = standardized value (how far a constituency deviates from the national mean, in standard deviation units). <b>Y-axis</b> = spatial lag (the weighted average of its neighbors' standardized values). The <b>gold regression line's slope = Moran's I</b>. <b>Four quadrants</b>: HH (top-right: high value, high neighbors = Hot Spot), LL (bottom-left: low value, low neighbors = Cold Spot), HL (bottom-right: high value surrounded by low = positive outlier), LH (top-left: low surrounded by high = negative outlier). Points far from the origin in HH/LL quadrants are the most strongly clustered locations. Points in HL/LH are the most interesting analytically: they represent constituencies where local factors override regional trends. <b>Policy</b>: HL/LH outliers (e.g., a high-turnout constituency in a low-turnout region) should be studied as models of what works.",

"40":"<b>Turnout Swing 2019 to 2024</b>: change in voter turnout between elections. <b>Red = turnout dropped</b> (voter disengagement). <b>Blue = turnout rose</b>. National average: -1.4 percentage points. <b>Interpreting negative swing</b>: fewer people voted in 2024. Causes could include: voter fatigue, anti-incumbency apathy (voters dislike all options), logistical barriers (weather, distance), or deliberate abstention as protest. <b>Interpreting positive swing</b>: mobilization efforts succeeded, or new voters entered (demographic turnover). <b>Spatial clustering</b> of disengagement (visible red clusters in parts of UP, Gujarat) suggests regional rather than random drivers. <b>Policy</b>: the ECI should conduct post-election surveys in high-negative-swing constituencies to diagnose causes, then deploy targeted Get-Out-The-Vote interventions.",

"41":"<b>Center vs Periphery</b>: victory margin vs distance from Delhi (degrees). Tests Stein Rokkan's (1970) <b>core-periphery model</b> of political geography, which hypothesizes that the political center exerts systematic influence on peripheral regions. <b>Finding</b>: no strong linear relationship, but variance changes. Near Delhi, margins range widely (some very safe NDA seats, some fiercely competitive). Far from Delhi (south, northeast), the distribution is more uniform. <b>Interpretation</b>: the lack of distance decay is actually a positive sign for Indian democracy: it means national politics is not simply radiating from a Delhi bubble. <b>Alliance coloring</b> reveals that NDA dominates near Delhi while INDIA is more prevalent at greater distances, consistent with the North-South political divide.",
}

WOMEN = {
"66":"<b>The Gauntlet</b>: funnel from ~8,360 candidates to 458 women to 133 who saved their deposit to 47 winners. <b>Deposit forfeiture</b>: candidates receiving <1/6 of total votes lose their security deposit (Rs 25,000 for General, Rs 12,500 for SC/ST). This is a formal indicator that the candidate was not competitive. <b>71% of women candidates forfeited</b>. This is far higher than the male forfeiture rate (~55%), suggesting that many women are fielded as <b>token candidates</b> by fringe parties with no real campaign support. <b>Policy</b>: parties should be required to provide minimum campaign infrastructure (funding, media time, organizational support) to any candidate they nominate. A 'nomination responsibility' mandate would prevent symbolic-only nominations that set women up to fail.",

"67":"<b>Gender Gap in the Electorate</b>: female voters per 1,000 male voters by state. <b>Parity = 1000</b>. <b>Green = above parity</b>. <b>Red = below</b>. Bihar (907) means there are 93 fewer women registered to vote for every 1,000 men. Extrapolated to Bihar's total electorate, this represents approximately <b>4 million 'missing' women voters</b>. Causes: women not registered (male household members do not list them), women's names removed due to migration (married women moving to husband's village), and under-age registration patterns (boys are registered earlier). <b>Kerala (1,084)</b> shows the opposite: more women registered than men, reflecting higher female literacy, stronger women's autonomy, and systematic voter registration drives by women's organizations. <b>Policy</b>: voter registration drives specifically targeting women in states below 950, using women's self-help groups, ASHA workers, and anganwadi centers as registration points.",

"68":"<b>Deposit Forfeiture Massacre</b>: every woman candidate as a dot. <b>Red (325)</b>: lost deposit (<1/6 of votes). <b>Gold (86)</b>: lost but saved deposit (competitive). <b>Green (47)</b>: won. The red wall of 325 dots is the central visual. Most red dots cluster below 2% vote share, indicating <b>non-competitive candidacies</b>. Many are from parties like BSP, NOTA parties, or hyper-local outfits that field candidates for symbol recognition, not to win. <b>The gold dots</b> (86 women who lost but were competitive) represent the actual 'glass ceiling': women who ran real campaigns and came up short. <b>The green dots</b> (47 winners) cluster at 30-55% vote share, comparable to male winners. <b>Key finding</b>: when women are genuinely competitive (gold + green = 133), their success rate is respectable. The problem is that 325 of 458 women never had a chance to begin with.",

"69":"<b>State Scoreboard: Three Dimensions</b>. Left: women elected per state. Center: deposit forfeit rate (% of women candidates who lost their deposit). Right: voter gender ratio. <b>14 states elected zero women</b>. <b>Kerala's paradox</b>: best gender ratio (1,084) but zero women MPs in 2024. This proves that voter-level gender parity does NOT automatically translate to women winning seats. The pipeline breaks at the <b>party nomination stage</b>: Kerala's major parties (CPI(M), Congress, BJP) nominated very few women for Lok Sabha despite having large women voter bases. <b>Policy</b>: mandatory party-level quotas (requiring parties to nominate at least 33% women) are more effective than voter-level interventions because the bottleneck is not voter willingness to elect women but party willingness to nominate them.",

"70":"<b>Women Candidature Terrain 3D</b>: height = % women candidates per constituency. Color: red (zero) through green (25%+). Red X on the floor = zero women ran. <b>The 3D perspective makes the sparsity visceral</b>: most of India is a flat red desert at z=0, with occasional green peaks. The peaks cluster in urban areas and southern states. <b>Spatial interpretation</b>: women's candidature follows a <b>core-periphery pattern</b> within India, with cores in metropolitan and southern areas and peripheries in the Hindi heartland. This mirrors the broader development gradient but is even more extreme: while economic indicators show gradual transitions, women's political participation shows a near-binary spatial divide.",
}

DELIM = {
"71":"<b>Delimitation Simulator</b>: drag slider from 543 to 1000 total seats. Each frame shows population-proportional reallocation using the <b>Webster/Sainte-Lague method</b> (a divisor method where each state's population is divided by 1, 3, 5, 7... and seats allocated to the highest quotients). <b>Gold diagonal = no change</b>. Points above = states gaining seats (northern, high-population-growth states). Points below = states losing (southern, low-growth states). <b>The animation reveals the zero-sum nature of delimitation</b>: southern states (red) consistently fall below the diagonal because they controlled population growth through investment in women's education, healthcare, and family planning. <b>Policy options</b>: (1) increase total seats to 700-1000 (reduces pain but does not eliminate it), (2) weight criteria beyond population (area, literacy, HDI, fiscal contribution), (3) freeze the current ratio indefinitely (as India did 1976-2026), (4) create compensating mechanisms in the Rajya Sabha or Finance Commission. Each has tradeoffs between democratic equality (one-person-one-vote) and federalism (protecting responsible states).",

"73":"<b>Women's Reservation Simulator</b>: slider 0-100%. At 0%: current reality (8.7% women MPs, 47 seats). At 33% (the actual Women's Reservation Bill): ~180 guaranteed women seats. At 50%: ~272. At 100%: all 543. <b>The gap between 47 and 180 quantifies 75 years of democratic deficit</b>. India has had universal suffrage since 1950, yet women's representation has never exceeded 12%. By comparison: Rwanda (61%), Bolivia (46%), Sweden (46%), South Africa (46%) all achieved >40% through some form of quota or reservation. <b>The evidence base</b> (Chattopadhyay and Duflo, 2004, studying panchayati raj reservations) shows that women leaders invest more in public goods (water, sanitation, roads) and are less corrupt than male counterparts. Reservation is not just symbolic representation; it produces measurably different policy outcomes.",

"74":"<b>Moran's I Criteria Explorer</b>: two curves showing how spatial clustering (Moran's I) changes as the weight between delimitation criteria shifts. <b>Red curve</b>: area vs population. <b>Cyan curve</b>: women voters vs fiscal returns. <b>Lower Moran's I = more equitable spatial dispersion</b> (the goal). <b>Higher I = more clustering</b> (unfair geographic concentration). <b>Negative I = anti-clustering</b> (ideal: systematically different values near each other, meaning no region is homogeneously advantaged). The curves show that area-weighted allocation produces HIGHER Moran's I (more clustering, because large-area states cluster in Rajasthan, MP, NE). Population-weighted is slightly better. Fiscal-returns-based criteria produce consistently lower clustering. <b>Policy insight</b>: the optimal delimitation formula would MINIMIZE Moran's I, meaning the formula should be chosen to produce the most spatially equitable distribution of representation. This is a novel application of spatial statistics to constitutional design.",

"75":"<b>Punishment Value (3D)</b>: X = fiscal return (Rs per 100 paid), Y = female voter %, Z = Lok Sabha seats. <b>Color = Punishment Value</b>, calculated as: <code>PV = 1 - 0.35 x (fiscal_return / 100)</code>. The 0.35 factor represents the estimated women's share of India's tax base (women are ~35% of taxpayers due to higher exemption slabs and lower formal workforce participation). A <b>PV near 1.0</b> (deep red) means the state faces maximum penalty: it pays the most tax, gets the least back, and the women's share of that fiscal loss is uncompensated. Tamil Nadu (PV = 0.90) and Maharashtra (PV = 0.90) are the most 'punished'. <b>Policy proposal</b>: earmark 35% of each state's fiscal transfer gap (the difference between what it pays and what it receives) for women's welfare programmes (safety, healthcare, education, political empowerment). This would create a direct link between fiscal responsibility and women's development outcomes.",

"76":"<b>Representation Inequality</b>: electors per seat by state, animated from 543 to 1000 seats. <b>Perfect equity = all bars identical</b>. At 543: UP has ~2.4 million voters per seat while Sikkim has ~0.4 million. A vote in Sikkim is worth <b>6 times</b> a vote in UP. This is the most fundamental democratic inequality in India, more extreme than the US Senate's state-size bias. <b>As total seats increase toward 1000</b>, bars equalize because proportional allocation converges toward equal per-capita representation. <b>Policy</b>: the question is whether India values pure proportional representation (one person, one vote, requiring ~800-1000 seats) or federal protection of smaller states (accepting some inequality, as the current 543-seat system does).",

"77":"<b>Fiscal Spine</b>: states connected south-to-north by latitude. <b>Size = Lok Sabha seats</b>. <b>Color = fiscal return</b> (red = contributor, green = recipient). The spine visually traces India's <b>fiscal gradient</b>: red nodes (contributors) at the southern end, transitioning to green (recipients) at the northern end. The transition happens roughly at the Vindhya range latitude (~23.5N), which also marks the linguistic divide (Dravidian vs Indo-Aryan), the demographic divide (low vs high fertility), and the development divide (higher vs lower HDI). <b>Policy insight</b>: this is not a coincidence. The fiscal, demographic, linguistic, and developmental divides are all <b>spatially co-located</b>, creating a compound geographic identity that makes the North-South debate feel existential rather than merely administrative.",

"78":"<b>Democratic Real Estate Treemap</b>: Region > State. <b>Area = Lok Sabha seats</b> (more seats = bigger rectangle). <b>Color = fiscal return</b> (red = contributor, green = recipient). Central and East regions (green, large rectangles: UP 80, Bihar 40, MP 29) receive the most fiscal transfers AND have the most seats. Southern region (red, smaller rectangles: TN 39, KA 28, KL 20) pays the most AND has fewer seats. The treemap makes the <b>double whammy</b> spatial: red rectangles (contributors) are literally smaller than green rectangles (recipients). Click any region to drill into state-level detail.",

"79":"<b>Fiscal Returns vs Women's Representation</b>: animated bubble, reservation slider 0-100%. <b>X = fiscal return</b> (linear scale). <b>Y = effective women %</b>. <b>Key finding</b>: as reservation increases (drag slider), ALL bubbles rise uniformly. But the X-axis spread (fiscal return from Rs 15 to Rs 510) does NOT change. <b>This proves that reservation fixes the gender gap but does NOT fix the fiscal gap</b>. The two problems require separate policy interventions: (1) Women's Reservation Bill for gender, (2) Finance Commission formula reform for fiscal equity. Neither can substitute for the other.",

"80":"<b>Constituency Clustering: Women Candidates</b>: every constituency color-coded by % women candidates. Continuous scale: deep red (0%) through orange (5%) through yellow (10%) through green (25%+). <b>The spatial clustering</b> is stark: red zones (no or few women) in central UP, rural Bihar, Rajasthan, and parts of Maharashtra. Green pockets in Delhi, Mumbai, Kolkata, Bangalore, and much of southern India. The pattern mirrors India's <b>Gender Development Index</b>: the same states with the worst sex ratios, lowest female literacy, and highest child marriage rates are the ones where women cannot enter politics. <b>This is not just correlation</b>: the causal mechanism runs through social norms (patriarchal gatekeeping), party structures (male-dominated selection committees), and spatial factors (large, rural constituencies where campaigning requires mobility that women lack).",
}

# 3D and immersive charts
IMMERSIVE = {
"42":"<b>Political Cylinder (3D)</b>: 543 constituencies on a rotating cylinder. <b>Height = latitude</b> (south bottom, north top). <b>Angle = longitude</b>. <b>Color = alliance</b>. This is a <b>cylindrical equidistant projection</b> that unrolls India's geography onto a navigable 3D surface. The projection preserves the North-South ordering (vertical) while wrapping East-West (angular). <b>Pink octahedra = women winners</b>, making their sparse distribution (~12% of nodes) visually striking. <b>Interpretation</b>: the cylinder immediately reveals the political divide. The lower half (south) is blue (INDIA alliance). The upper half (north) is saffron (NDA). The mid-section (Maharashtra, Telangana, Karnataka) is mixed, representing the competitive battleground. Drag to rotate and observe how the transition zone wraps around the cylinder.",

"43":"<b>Development Globe (3D)</b>: 196 countries on a rotating sphere, bars extruding outward. Three switchable metrics: GDP per capita, life expectancy, fertility. <b>GDP mode</b>: Northern Hemisphere towers over the South. <b>Fertility mode</b>: the pattern inverts (Africa/South Asia tower). <b>Life expectancy mode</b>: a compromise between the two. The globe perspective uniquely reveals that development challenges are <b>hemispherically clustered</b>: virtually all low-GDP, high-fertility, low-lifeExp countries are in the Southern Hemisphere's tropical belt. This geographic concentration means that international development cooperation, climate adaptation funding, and health infrastructure investment can be spatially targeted with high efficiency.",

"44":"<b>Double Helix (3D)</b>: NDA and INDIA alliance constituencies spiral in a DNA-like double helix. <b>The metaphor is deliberate</b>: India's political identity is encoded in a dual structure, not a simple binary. The two strands interweave in swing states (Maharashtra, Karnataka, Rajasthan), representing the dynamic, contested nature of Indian democracy. <b>Node size = victory margin</b>: large nodes are safe seats, small nodes are competitive. The helix reveals that safe seats for both alliances are geographically concentrated (top = NDA safe, bottom = INDIA safe) while competitive seats cluster in the middle turns.",

"45":"<b>Continental Development Space (3D)</b>: 196 countries in three simultaneous dimensions. <b>X = GDP per capita (log)</b>, <b>Y = Life Expectancy</b>, <b>Z = Fertility Rate</b>. No 2D projection information loss. Africa (cyan) forms a distinct cluster in the high-fertility, low-GDP, low-lifeExp octant. Europe (green) occupies the opposite octant. The 3D perspective reveals that some countries break expected patterns: Gulf states (high GDP, moderate lifeExp, low fertility) and Cuba (low GDP, high lifeExp, low fertility, reflecting its prioritization of healthcare) are visible as outliers. <b>Bubble size = population</b>: India and China dwarf all others.",

"46":"<b>Women + Area Hypothesis</b>: three panels. <b>Mann-Whitney U test</b>: a non-parametric test comparing two independent samples without assuming normality. It ranks all observations and tests whether one group's ranks are systematically higher. <b>Result</b>: women winners have significantly smaller constituencies (median 3,324 km2 vs men 4,073 km2, p < 0.05). <b>Interpretation</b>: women are more likely to win in smaller, denser (more urban) constituencies. This could reflect: (1) better media access in urban areas (women's campaigns benefit more from media than from physical rallies), (2) more educated electorates (research shows educated voters are more willing to vote for women), (3) party calculations (parties nominate women where they believe gender is electorally advantageous). <b>SC reserved seats</b> show 15.5% women representation (highest of any category), possibly because the reservation system disrupts normal male-dominated candidate selection.",

"47":"<b>3D Spatial Histogram</b>: bars rising from constituency locations over India. <b>Height = selected metric</b> (electorate ratio, turnout, or margin), switchable via buttons. This implements the TA's requirement of superimposing quantitative data onto geographic space. <b>Electorate ratio mode</b> shows dramatic North-South inequality: northern bars tower (UP, Bihar constituencies have 2x the national average electorate) while southern bars are shorter. <b>Turnout mode</b> shows the inverse: southern India has taller bars. <b>Policy</b>: the 3D visualization makes the case for delimitation reform more viscerally than any 2D chart. The towering northern bars literally represent voters whose vote is worth less.",

"48":"<b>Alliance LISA + Women Bivariate</b>. <b>Left panel</b>: LISA clusters on a binary NDA (+1) / INDIA (-1) coding. Moran's I = 0.37 (strong spatial autocorrelation of political alignment). 110 NDA strongholds (orange) and 112 INDIA strongholds (blue) identified at p < 0.05. <b>Right panel</b>: state-level bubble chart of NDA seat share vs women's representation. <b>Critical finding</b>: the two variables show NO significant correlation. NDA-dominated states and INDIA-dominated states have <b>equally poor</b> women's representation. This demolishes any argument that one alliance is inherently better for women's political inclusion. <b>Policy</b>: the Women's Reservation Bill must be implemented as a <b>non-partisan structural mandate</b> because neither alliance's voluntary behavior has produced adequate representation.",

"49":"<b>GDP Bar Chart Race</b>: top 15 nations racing 1992-2022. <b>Ireland's surge</b> reflects its role as a corporate tax haven (multinational profits booked in Ireland inflate GDP). <b>Qatar</b>: resource wealth concentrated in a tiny citizen population (80% of Qatar's residents are non-citizen workers not counted in per-capita calculations). <b>Singapore</b>: genuine productivity-driven growth in a city-state. <b>Policy caveat</b>: per-capita GDP rankings can be deeply misleading. Ireland's GDP is 2x its GNI (Gross National Income) because corporate profits leave the country. Median household income is a better welfare measure.",

"50":"<b>Electoral Swing 2019 vs 2024</b>: animated geo scatter toggling between elections. Bubbles morph in size (margin) and position as the map transforms. <b>214 constituencies changed party</b>. Key swings: NDA lost significant ground in UP (Samajwadi Party surge), Maharashtra (Shiv Sena split consequences), and Rajasthan. INDIA alliance consolidated in Tamil Nadu, Kerala, and West Bengal. <b>The animation's 1.5-second transition</b> makes the geographic pattern of change visible as a wave.",

"51":"<b>The Great Fertility Collapse</b>: year-by-year, 1990-2023 (33 frames). This is arguably <b>the single most important demographic animation ever produced</b>. Watch the entire global cloud migrate from upper-left to lower-right. Africa's descent is the most dramatic ongoing shift. By 2023, only Niger, Chad, Somalia, and DRC exceed 5 births/woman. <b>Policy</b>: the remaining high-fertility countries will determine global population trajectories. Investing in girls' secondary education in these 20-30 countries is the highest-leverage demographic intervention available to humanity.",

"52":"<b>Mortality Plunge (Animated Choropleth)</b>: under-5 mortality 1990-2022. Watch Sub-Saharan Africa gradually lighten from deep red (200+ per 1,000) toward orange (80-120). South Asia shows the most dramatic improvement (India: 130 to 27). <b>The acceleration post-2000</b> coincides with the Millennium Development Goals and massive increases in GAVI vaccination funding, Global Fund malaria programmes, and PEPFAR HIV/AIDS treatment. <b>Policy</b>: the MDG-era acceleration proves that internationally coordinated goals with funding commitments WORK. The SDG framework must maintain this momentum.",

"53":"<b>Continental Convergence (and Divergence)</b>: left panel shows life expectancy by continent (converging: Africa catching up). Right panel shows GDP per capita (diverging: gap widening). <b>Convergence</b> = lines coming together over time. <b>Divergence</b> = lines spreading apart. <b>This dual pattern is the central paradox of modern development</b>: health improvements have been democratized globally (through technology transfer, international aid, and public health knowledge), but economic improvements have NOT (market forces concentrate wealth geographically). <b>Policy</b>: health convergence proves that targeted interventions can overcome structural inequality. GDP divergence proves that markets alone cannot. Both insights should inform development strategy.",

"54":"<b>Women's LISA</b>: spatial clustering of women winners (Moran's I = 0.062, p < 0.001). Weak but statistically significant: women winners are slightly more likely to cluster spatially than random. <b>Right panel</b>: area vs voter density scatter. Women (pink diamonds) cluster in a specific zone: smaller area, higher density. <b>Policy implication</b>: parties could leverage the neighborhood effect by strategically nominating women in clusters where adjacent constituencies have elected women, creating a spatial 'beachhead' of women's representation that expands outward.",

"55":"<b>Party Flip Pulse (3D)</b>: 214 flipped constituencies pulse with golden rings (sinusoidal scale and opacity animation at different phases per constituency). Stable seats glow softly. <b>The pulsing pattern reveals geographic clustering of change</b>: western UP, Maharashtra, and parts of Rajasthan show dense pulsing (many flips concentrated together), while most of south and east India show stable, non-pulsing seats. <b>Policy</b>: the geographic clustering of flips suggests that swing dynamics operate at a regional, not national level. Campaign resources should be targeted at these oscillating zones.",

"56":"<b>Development Spiral (3D)</b>: Gapminder data 1952-2007. Countries trace helical paths through space-time. <b>Radius = log(GDP per capita)</b>: countries spiral outward as they get richer. <b>Height = life expectancy</b>: they rise as health improves. <b>The slider scrubs through years</b>, moving endpoint dots along their trajectory tubes. African countries produce tight, low spirals (little outward or upward movement). European countries produce wide, high spirals. The 3D spiral makes temporal development visible as a physical path you can walk along.",

"57":"<b>Coral Temporal Pulse</b>: reef map (top, 27 systems by threat level) paired with SST timeline (bottom, 1980-2024). The dual view links <b>cause</b> (bottom: accelerating ocean warming) to <b>effect</b> (top: reef systems under increasing thermal stress). <b>Mass bleaching intervals</b>: 1998-2010 (12 years), 2010-2016 (6 years), 2016-2024 (8 years). Recovery requires 10-15 years of cool conditions. If bleaching occurs every 6-8 years, reefs cannot recover between events, leading to permanent degradation. <b>Policy</b>: marine conservation must now incorporate <b>climate triage</b>, focusing limited resources on reefs with the highest thermal tolerance and genetic diversity.",

"58":"<b>Animated Inequality (Gini)</b>: 5-year bins, 1990-2020. <b>Latin America's improvement</b> (Gini declining from 55-60 to 45-50) reflects conditional cash transfer programmes (Brazil's Bolsa Familia, Mexico's Oportunidades) that directly redistributed income to the poorest 20%. <b>China's increase</b> (from 35 to 47) reflects the inequality cost of rapid market-driven growth: coastal regions surged while interior provinces lagged. <b>Policy lesson</b>: inequality trajectories are not determined by economic forces alone. Policy choices (redistributive taxation, social transfers, minimum wages) can push Gini in either direction. The data shows that countries with similar GDP growth rates can have opposite inequality trajectories depending on policy.",

"59":"<b>India Development Terrain (3D)</b>: 30 states as pillars. 8 switchable metrics. <b>The switching is the key feature</b>: click 'HDI' and Kerala/Goa tower while Bihar/UP are short. Click 'Sex Ratio' and the terrain reshapes: Haryana/Punjab shrink (terrible sex ratios) while Kerala stays tall. Click 'Food Production' and Punjab/UP dominate. <b>No state excels on all 8 dimensions</b>. Gujarat leads in GSDP but lags in HDI. Kerala leads in HDI but lags in GSDP. Tamil Nadu is strong across most metrics but not dominant in any single one. <b>Policy</b>: balanced development requires investment across all dimensions. GDP-only growth strategies (Gujarat model) leave health, gender, and environmental deficits that eventually constrain further growth.",

"60":"<b>India Food Geography 3D</b>: rice (green diamonds) and wheat (gold squares) at actual state lat/lon. <b>Height = production in million tonnes</b>. The sharp rice-wheat divide follows the <b>monsoon boundary</b>: rice dominates in the eastern/southern monsoon belt (Bengal, AP, Tamil Nadu), wheat dominates in the northwestern semi-arid zone (Punjab, Haryana, UP). This spatial specialization is a legacy of the <b>Green Revolution</b> (1960s-70s), which introduced high-yield dwarf wheat varieties suited to irrigated Punjab and Haryana, and hybrid rice varieties for the eastern plains. <b>Policy warning</b>: climate change threatens both: wheat in Punjab faces heat stress (every 1C warming reduces wheat yield 6-7%), rice in Bengal faces sea-level rise and salinization. Crop diversification and climate-resilient varieties are insurance against these spatially differentiated threats.",

"61":"<b>Literacy-Gender Helix (3D)</b>: two strands (literacy = cyan, sex ratio = magenta) intertwined, ordered by HDI. <b>Where both strands bulge outward</b> (Kerala): education and gender equity reinforce each other in a virtuous cycle. <b>Where they diverge</b> (Haryana: literacy strand extends normally, sex ratio strand collapses): education has NOT translated into gender equity. Haryana has ~77% literacy but a sex ratio of only 879 (one of the worst globally). This proves that <b>education alone is insufficient</b> for gender equity in the presence of deeply rooted son preference and sex-selective practices. <b>Policy</b>: Haryana needs targeted enforcement of the PCPNDT Act (Pre-Conception and Pre-Natal Diagnostic Techniques Act) against sex-selective abortion, cash incentive schemes for girl children (like Ladli), and cultural campaigns challenging son preference. The helix metaphor makes the mismatch tangible.",

"62":"<b>Constituency Aurora (3D)</b>: 543 breathing particles. <b>Oscillation amplitude = turnout</b> (higher turnout = bigger vertical breathing motion). <b>Glow intensity = victory margin</b>. <b>Vertical beams = high-margin seats</b>. Alliance-colored. The aurora effect reveals geographic democracy as a living organism: southern India breathes with high amplitude (engaged electorate), the Hindi belt oscillates gently (lower turnout). Vertical beams (safe seats) cluster in certain regions. <b>The metaphor</b>: democracy is not static; it pulses, breathes, and has zones of vitality and dormancy.",

"63":"<b>India Socioeconomic 3D</b>: X=Literacy, Y=GSDP/capita, Z=HDI. <b>Drop lines</b> to the HDI floor make the Z-axis readable. Southern states (red) cluster at high literacy, moderate GSDP, high HDI. Northern states (green/cyan) cluster lower on all three. Delhi is an outlier: high GSDP but moderate HDI (inequality reduces the average person's experience of wealth). <b>Bihar occupies the lowest position on all three axes</b>. <b>Policy</b>: HDI is a better welfare metric than GSDP because it incorporates health (life expectancy) and education (schooling years) alongside income. States that focus solely on GDP growth (as measured by GSDP) can have poor HDI if growth is concentrated among elites.",

"64":"<b>Gender-Development Nexus 3D</b>: X=Sex Ratio (F per 1000 M), Y=IMR (reversed: lower=better=higher on screen), Z=Literacy. <b>Color = sex ratio</b> (red=dangerous, green=healthy). Kerala sits at the ideal corner: green (1,084), high (low IMR), high literacy. Haryana sits at the alarming opposite: red (879), lower (higher IMR), moderate literacy. <b>The reversed Y-axis</b> is crucial: it makes 'up = better' intuitive for a variable where lower values are desirable. <b>Policy</b>: states in the red zone (Haryana, Punjab, Delhi, Gujarat) all have sex ratios below 920, indicating widespread sex-selective practices. These states need: (1) strict PCPNDT Act enforcement, (2) conditional cash transfers for girl children, (3) public awareness campaigns, and (4) economic empowerment programmes for women to shift the calculus of son preference.",
}

# Build all entries
def make_guide(title, tagline, body):
    return f'<h2>{title}</h2>\n<p class="tagline">{tagline}</p>\n{body}'

# Process remaining charts into G dict
for num, data in REMAINING.items():
    title, tagline, body, policy = data
    G[num] = make_guide(title, tagline, f'<p>{body}</p>\n<div class="hl warn">{policy}</div>')

for num, body in COMPACT.items():
    G[num] = f'<p>{body}</p>'

for num, body in INDIA_3D.items():
    G[num] = f'<p>{body}</p>'

for num, body in WOMEN.items():
    G[num] = f'<p>{body}</p>'

for num, body in DELIM.items():
    G[num] = f'<p>{body}</p>'

for num, body in IMMERSIVE.items():
    G[num] = f'<p>{body}</p>'

# Charts 13-21, 23-36 use the COMPACT dict (already added above)

# Inject into all charts
count = 0
for filename in sorted(os.listdir(VIZ_DIR)):
    if not filename.endswith(".html") or filename == "index.html":
        continue
    num = filename.split("_")[0]
    content = G.get(num)
    if not content:
        print(f"  NO ANNOTATION: {filename}")
        continue
    
    filepath = os.path.join(VIZ_DIR, filename)
    html = open(filepath).read()
    if 'ATLAS-GUIDE-START' in html:
        continue
    
    guide_block = GUIDE_CSS + '\n<div class="guide"><div class="guide-inner">\n'
    guide_block += content
    guide_block += '\n</div></div>\n' + GUIDE_END + '\n'
    
    if "</body>" in html:
        html = html.replace("</body>", guide_block + "</body>")
    else:
        html += guide_block
    
    open(filepath, 'w').write(html)
    count += 1

print(f"\nInjected deep guides into {count} charts")
